# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: traefik-kop
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: ./bin/traefik-kop/
    binary: traefik-kop
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - darwin
    goarch:
      - amd64
      # - arm
      - arm64
    # goarm:
      # - "6"
      # - "7"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

